### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) in nativeClear

### ISSUE THREAD

**Issue by MGaetan89** [realm/realm-java#5138]
On my application, I am seeing the following natice crash.
I was not able to reproduce it, and it was only reported on one device and Android version (see below).
I don't think it is a critical issue, considering the number of report, but maybe you can do something about it in a future release or guide me in the right direction.

The stacktrace I have in the Play Console is:
```
backtrace:
  native: pc 00000000001cfdb0  /data/app/com.myapp-1/lib/arm64/librealm-jni.so
  native: pc 00000000001d6404  /data/app/com.myapp-1/lib/arm64/librealm-jni.so
  native: pc 00000000001daaf0  /data/app/com.myapp-1/lib/arm64/librealm-jni.so
  native: pc 00000000001df724  /data/app/com.myapp-1/lib/arm64/librealm-jni.so
  native: pc 00000000000c587c  /data/app/com.myapp-1/lib/arm64/librealm-jni.so
  native: pc 000000000004ae24  /data/app/com.myapp-1/lib/arm64/librealm-jni.so (Java_io_realm_internal_Collection_nativeClear+48)
  native: pc 00000000000ed354  /data/app/com.myapp-1/oat/arm64/base.odex (deleted) (offset 0xb02000)
```

#### Version of Realm and tooling

Realm version(s): **3.4.0**

Realm sync feature enabled: **no**

Android Studio version: **3.0-beta2**

Which Android version and device: **Android 7.0** on **Galaxy S7 Edge** (hero2lte)
